### ISSUE TITLE
Error'd on "NVIDIA" | Support Concern

### ISSUE THREAD

**Issue by fnstart** [S4NKALP/hyprland#2]
In short, I have two GPU's one is an RX 6800 XT (AMD) and an secondary(The GPU in question) for KVM stuff.

- Had to manually edit the bash script and remove the check, since you're technically not checking for what's being used as the main one.

- Line in Question: `lspci 2>/dev/null | grep -i 'NVIDIA' &>/dev/null`
- It unfortunately seem's I won't be able to use even though it's an fresh install of hyprland and Arch in whole, from just looking at the sddm & ctl service error(s)

```
[smith@black bin]$ lspci 2>/dev/null | grep -i 'NVIDIA' 
05:00.0 VGA compatible controller: NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)
```

```
[smith@black bin]$ lspci 2>/dev/null | grep -i 'AMD' 
03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] (rev c1)
```

```
[smith@black ~]$ fastfetch
GPU: AMD Radeon RX 6800 XT [Discrete]
```

```
[smith@black ~]$ neofetch
GPU: NVIDIA GeForce GTX 1070 
GPU: AMD ATI Radeon RX 6800/6800 XT / 6900 XT 
```

**Comment by S4NKALP** [comment]
the installer script is not for NVIDIA GPUs and willnot support Vms

**Comment by S4NKALP** [comment]
i don't have a NVIDIA machine
